Home work6
YuriyFilimonov/Programming pull request #4
Opened 2020-01-31 13:31 UTC by YuriyFilimonov

Задание к уроку №6 выполнено в полном объеме.
На сработала конструкция List<PetAnimal> petAnimals = new Arrays.asList(cat1, cat2, cat3, dog1, dog2, dog3); в файле  HomeZoo.
Такая же конструкция в прошлом ДЗ работает без проблем:
List<Staff> staffList = Arrays.asList(abramovA, borisovB, vasilevV, gavrilovG, denisovD);
Где ошибка?

2020-02-04 21:52 UTC, OKrylov requested changes
В целом все хорошо, но не увидел по коду 4 задания, чтобы животные пытались выполнить действия, в зависимости от значения препятствия и их способностей у них получалось или же нет.

`List petAnimals = new Arrays.asList(cat1, cat2, cat3, dog1, dog2, dog3);` - new здесь лишнее, мы его используем только для конструкторов, чтобы создать новый объект

2020-02-04 21:52 UTC, OKrylov commented on src/HomeWork6/Cat.java
> +    protected int setMaxRun() {
set обозначает задать значение полю класса, которое обычно передается в качестве параметра. У вас здесь скорее get

2020-02-04 21:52 UTC, OKrylov commented on src/HomeWork6/Cat.java
> +    protected int setMaxSwim() {
set обозначает задать значение полю класса, которое обычно передается в качестве параметра. У вас здесь скорее get

2020-02-04 21:52 UTC, OKrylov commented on src/HomeWork6/Dog.java
> +    protected int setMaxRun() {
set обозначает задать значение полю класса, которое обычно передается в качестве параметра. У вас здесь скорее get

2020-02-04 21:52 UTC, OKrylov commented on src/HomeWork6/Dog.java
> +    protected int setMaxSwim() {
set обозначает задать значение полю класса, которое обычно передается в качестве параметра. У вас здесь скорее get

2020-02-05 09:44 UTC, YuriyFilimonov commented on src/HomeWork6/Cat.java
> +    protected int setMaxRun() {
Согласен, конечно, надо ставить get. Я несколько изменил логику заданий 2 и 3. Люди ведут исследования животных и описывают характеристики, свойства каждого вида. Так, в описание входит и максимальная скорость бега, длина и высота прыжка и т.д. Поэтому, я взял установленные максимальные значения характеристик и set относится к значению установленные.

2020-02-05 10:05 UTC, YuriyFilimonov commented on src/HomeWork6/Cat.java
> +    protected int setMaxSwim() {
Согласен, конечно, надо ставить get. Я несколько изменил логику заданий 2 и 3. Люди ведут исследования животных и описывают характеристики, свойства каждого вида. Так, в описание входит и максимальная скорость бега, длина и высота прыжка и т.д. Поэтому, я взял установленные максимальные значения характеристик и set относится к значению установленные.

2020-02-05 10:05 UTC, YuriyFilimonov commented on src/HomeWork6/Dog.java
> +    protected int setMaxRun() {
Согласен, конечно, надо ставить get. Я несколько изменил логику заданий 2 и 3. Люди ведут исследования животных и описывают характеристики, свойства каждого вида. Так, в описание входит и максимальная скорость бега, длина и высота прыжка и т.д. Поэтому, я взял установленные максимальные значения характеристик и set относится к значению установленные.

2020-02-05 10:05 UTC, YuriyFilimonov commented on src/HomeWork6/Dog.java
> +    protected int setMaxSwim() {
Согласен, конечно, надо ставить get. Я несколько изменил логику заданий 2 и 3. Люди ведут исследования животных и описывают характеристики, свойства каждого вида. Так, в описание входит и максимальная скорость бега, длина и высота прыжка и т.д. Поэтому, я взял установленные максимальные значения характеристик и set относится к значению установленные.

2020-02-05 10:05 UTC, YuriyFilimonov commented on src/HomeWork6/Cat.java
> +    protected int setMaxRun() {
Согласен, конечно, надо ставить get. Я несколько изменил логику заданий 2 и 3. Люди ведут исследования животных и описывают характеристики, свойства каждого вида. Так, в описание входит и максимальная скорость бега, длина и высота прыжка и т.д. Поэтому, я взял установленные **максимальные значения характеристик** (setMaxRun) и set относится к значению установленные.
Вопрос 2: животные пытались выполнить действия, в зависимости от значения препятствия и их способностей у них получалось или же нет.
Здесь я переформатировал задачу исходя из того, что существуют максимальные характеристики для каждого вида животных (константы MAX_RUN, MAX_SWIM, методы setMaxRun, setMaxSwim) и фактические значения, которые показывают конкретные экземпляры (Класса) - cat1, cat2..., попытки бегать и плавать реализованы в  коде HomeZoo.
        int countCat, coutnDog;
        countCat = coutnDog = 0;
        for (PetAnimal petAnimal : zoo) {
            petAnimal.setLenRun(random.nextInt(petAnimal.setMaxRun()+1)); //животные бегают
            petAnimal.setLenSwim(random.nextInt(petAnimal.setMaxSwim()+1));//прыгают
            if (petAnimal instanceof Cat) {
                countCat++;
            } else {
                coutnDog++;
            }
        }
        System.out.println("В домашнем зоопарке всего: " + zoo.size() + " животных, в том числе " + countCat
                + " кошек и " + coutnDog + " собак.");

        for (PetAnimal petAnimal : zoo) {//информация об успехах в активности животных
            petAnimal.printAction();
        }

2020-02-10 07:30 UTC, merged